### PR TITLE
Initial fix for z-index

### PR DESCRIPTION
**Pull request by xiaozdezhu**
Move audio from drag function to componentWillUpdate to avoid delay for dragging
Remove onTouchStart() 
When start dragging a piece, call setZIndex immediately to make that piece closest to user.

### CODE REVIEW

**Comment by xiaozdezhu** [comment]
I move the setState operation to close showCardOptions menu from onDragStart to onDragEnd. And for onDragStart I add a functions to updateZindex, so I keep both of them.

**Comment by yoav-zibin** [comment]
No, please don't add back the onDragEnd.
Just have onTouchEnd and onDragStart.

You can move the "setState operation to close showCardOptions menu" to
onTouchEnd

**Comment by xiaozdezhu** [comment]
I have made it that when start dragging a piece, call setZIndex immediately to make that piece closest to user. However, shuffleDeck still doesn't work because I still don't know how to make cards displayed in their correct z-index.
I have tried 2 methods:
1. I add a function 
```
sortZIndexofPieces() {
    this.mutableMatch.matchState.sort((a, b) => {
      return a.zDepth - b.zDepth;
    });
  }
```
And I call it before rendering pieces. However in that case the pieces sequence in matchState is never the same as pieces sequence in gameSpec anymore. Unless we add a field for pieceState to record its original sequence? 
2. I looked into the code of GamePortalReact, it seems their solution is to call imageNode.setZindex for all pieces after rendering(in componentDidUpdate) if I didn't misunderstood anything.
I tried it and add
```
componentDidUpdate(){
    for (let i = 0; i < this.mutableMatch.matchState.length; i++) {
      this.updateZIndex(i, this.mutableMatch.matchState[i].zDepth);
    }
  }
```
However, I get this error
image

Anyway I am still trying to make it work...
Please tell me if I misunderstand anything.

**Comment by yoav-zibin** [comment]
Use this function I just added:


sortMatchStateByZ(): ({originalIndex: number, pieceState: PieceState}[]) {
const state: MatchState = this.mutableMatch.matchState;
return state.map((pieceState, originalIndex) => ({
originalIndex, pieceState
})).sort((a,b) => a.pieceState.zDepth - b.pieceState.zDepth);
}

**Pull request merged**
